
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "390585b0-37ba-493c-bc27-7c0b243f231f"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "ea560db0-3ece-40a9-8ccc-35f760f52258",
    "account_id_to": "74278310-67af-4279-bf39-14d5eac4e9ca",
    "amount": 1
}