
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "5c1898f9-6831-4401-bc13-aec918913f2f"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "5c1898f9-6831-4401-bc13-aec918913f2f",
    "account_id_to": "541eb5fa-8247-49cf-a5d1-3c23b1734f1c",
    "amount": 100
}